--TRUNCATE TABLE JOB_DESCRIPTION;
CREATE TABLE IF NOT EXISTS JOB_DESCRIPTION (
    JOBID INT PRIMARY KEY,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(255)
);
INSERT INTO JOB_DESCRIPTION (JOBID , TITLE, DESCRIPTION) VALUES (5000, 'Software Engineer', 'Developing software applications');
INSERT INTO JOB_DESCRIPTION (JOBID, TITLE, DESCRIPTION) VALUES (5001, 'Project Manager', 'Managing projects');
INSERT INTO JOB_DESCRIPTION (JOBID, TITLE, DESCRIPTION) VALUES (5002, 'Product Manager', 'Managing products');
INSERT INTO JOB_DESCRIPTION (JOBID, TITLE, DESCRIPTION) VALUES (5003, 'Data Analyst', 'Analyzing data');
INSERT INTO JOB_DESCRIPTION (JOBID, TITLE, DESCRIPTION) VALUES (5004, 'Marketing Manager', 'Managing marketing');